theme: jekyll-theme-cayman
title: Dartmouth Focus App Documentation
description: Comprehensive documentation for the Dartmouth Focus App, including ML features and focus tracking
show_downloads: true
google_analytics:
markdown: GFM

# Build settings
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# Navigation
nav:
  - title: Home
    url: /
  - title: Installation
    url: /#installation
  - title: Project Structure
    url: /#project-structure
  - title: Running the App
    url: /#running-the-app
  - title: Development Guidelines
    url: /#development-guidelines
  - title: Machine Learning Features
    url: /#machine-learning-features 