platform :ios, '14.0'
use_frameworks!

project 'DartmouthFocusApp/DartmouthFocusApp.xcodeproj'

target 'DartmouthFocusApp' do
  # UI Dependencies
  pod 'SnapKit'
  pod 'Kingfisher'
  
  # Navigation
  pod 'FloatingPanel'
  
  # Utilities
  pod 'RxSwift'
  pod 'RxCocoa'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end 